fix: eslint max depth warnings
defenseunicorns/pepr pull request #1255
Opened 2024-10-10 05:00 UTC by tamirazrab

## Description
Fixes eslint `max-depth` warnings in different files. 

Left out` helper.ts` purposely not sure how to remove nesting there.

## Related Issue

Fixes #1249 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging
- [X] Unit, [Journey](https://github.com/defenseunicorns/pepr/tree/main/journey), [E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples), [docs](https://github.com/defenseunicorns/pepr/tree/main/docs), [adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or updated as needed
- [X] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request) followed

2024-10-11 17:56 UTC, cmwylie19 commented
We need to hold off on this PR until our release next week. Thank you for your contribution!

2024-10-15 19:03 UTC, samayer12 commented on src/cli/init/index.ts
> +            // }
We should double-check the error behavior here when `code` is not a binary on the system

2024-10-15 19:07 UTC, samayer12 commented on src/lib/validate-processor.ts
> +        };
What happens if `resp` does not include either property but is otherwise okay? Is that possible? We should look into that before merging.

2024-10-15 19:11 UTC, samayer12 requested changes
Linter warnings are resolved, thank you! Left a couple comments for questions that the maintainers can consider prior to merging.

2024-10-21 18:50 UTC, cmwylie19 commented
can you please run `npm run format:fix` to try and fix the formatting issues? @tamirazrab

2024-10-30 12:22 UTC, tamirazrab commented
> can you please run `npm run format:fix` to try and fix the formatting issues? @tamirazrab

Yes I did, sorry for delay, most warning aren't related to `max-depth` other than `pepr/src/lib/helpers.ts` which I'm not really sure how to proceed refactoring it.

2024-10-30 15:01 UTC, samayer12 commented
@tamirazrab, thanks for doing the bulk of the work resolving the max-depth warnings! I'm gonna knock out the last few things and update the branch for us since we've had several changes over the past few weeks.

2024-10-31 15:24 UTC, samayer12 commented on src/cli/init/index.ts
> +            // }
This is required, otherwise we fail the test and log an exception.

2024-10-31 15:40 UTC, samayer12 commented
There are broader issues with test-coverage in the refactored files that we already know about, accepting the small overall decrease to gain linter resolutions.

2024-10-31 15:40 UTC, merged