chore: add typing support to regex-related adjudicators
defenseunicorns/pepr pull request #1484
Opened 2024-11-22 20:20 UTC by samayer12

## Description

This PR adds typing support for regex-related adjudicators. Merge this in after #1402. 

End to End Test:    
(See [Pepr Excellent Examples](https://github.com/defenseunicorns/pepr-excellent-examples))

## Related Issue

Relates to #1397, 1402

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging
- [x] Unit, [Journey](https://github.com/defenseunicorns/pepr/tree/main/journey), [E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples), [docs](https://github.com/defenseunicorns/pepr/tree/main/docs), [adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or updated as needed
- [x] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request) followed

2024-12-03 13:27 UTC, cmwylie19 commented on src/lib/capability.ts
> +    function InNamespaceRegex(...namespaces: string[]): BindingWithName<T> {
```suggestion
    function InNamespaceRegex(...namespaces: string[]): BindingWithName<T> {
```

This is a breaking change to the Pepr API that is in production and being used in delivery. I could be mistaken but i think we chatted about changing the regexes and decided against due to the need to serialize the bindings during the forking process

2024-12-03 13:27 UTC, cmwylie19 requested changes
This is a breaking change to the Pepr API that is in production and being used in delivery.

2024-12-05 16:51 UTC, samayer12 commented on src/lib/capability.ts
> +    function InNamespaceRegex(...namespaces: string[]): BindingWithName<T> {
That's right, we're serializing data from a string so we can't force the data to be a `RegExp` at the moment.

2024-12-16 17:47 UTC, samayer12 commented
It has been awhile since this was created, we'll restart off of main since the journey tests are failing.

2024-12-16 17:47 UTC, closed without merging