chore: update favicon and fix Netlify config.
defenseunicorns/pepr pull request #343
Opened 2023-10-25 17:57 UTC by bdfinst

2023-10-25 18:02 UTC, btlghrants requested changes
I think the 512 images have some sizing issues..?  Maybe?  Glad to be wrong if that's not the case.

2023-10-25 18:02 UTC, btlghrants commented on website/static/favicons-new/android-chrome-512x512.png
Seems there's an _awful_ a lot whitespace in this image... izzat right?

2023-10-25 18:02 UTC, btlghrants commented on website/static/favicons-new/android-chrome-maskable-512x512.png
Same as above -- lot's of whitespace..?

2023-10-25 18:54 UTC, btlghrants commented on website/static/favicons-new/android-chrome-512x512.png
Figured -- and fixed -- reason.  The image generator in use (https://cthedot.de/icongen) needed the source SVG to have a width & height defined on it's <svg> tag.  For whatever reason.

2023-10-25 18:54 UTC, btlghrants commented on website/static/favicons-new/android-chrome-maskable-512x512.png
Figured -- and fixed -- reason.  The image generator in use (https://cthedot.de/icongen) needed the source SVG to have a width & height defined on it's <svg> tag.  For whatever reason.

2023-10-25 18:59 UTC, btlghrants requested changes
LTGM, mostly.

What's the reason for the folder being `favicon-new` instead of just using the existing `favicon` folder though?  Happy to merge once I'm clear on that.

2023-10-25 20:24 UTC, bdfinst commented
> LTGM, mostly.
> 
> What's the reason for the folder being `favicon-new` instead of just using the existing `favicon` folder though? Happy to merge once I'm clear on that.

I fixed that. Srry.

2023-10-26 13:17 UTC, btlghrants approved these changes
LGTM.

Gotta say too, that large-form dragon looks _frickin' sweet_ next to that old, fuzzy Dougie.  Big upgrade, yay.  :1st_place_medal:

2023-10-26 13:17 UTC, merged