chore: update logo image in header
defenseunicorns/pepr pull request #420
Opened 2023-12-05 19:17 UTC by schaeferka

## Description

Updated the logo image used in the header to an svg file that includes the word mark.

## Related Issue

Fixes #342

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/pepr/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

2023-12-05 19:18 UTC, schaeferka commented
The Pepr horizontal wordmark for dark backgrounds svg file that I have looks a little pixelated. If there is a better svg file to use, I can easily update the header.

2023-12-06 17:22 UTC, schaeferka commented
Updated to new svg file:

![Screenshot 2023-12-06 at 09 54 08](https://github.com/defenseunicorns/pepr/assets/49598208/a2a5dd18-e015-4e78-8d1d-00e0c7ea2e5e)

2023-12-06 19:02 UTC, cmwylie19 submitted a review, later dismissed
lgtm

2023-12-06 20:42 UTC, btlghrants requested changes

2023-12-06 20:42 UTC, btlghrants commented on website/assets/scss/_styles_project.scss
> +}
```suggestion
.td-navbar .navbar-brand svg {
    width: fit-content;
}
```

Since CSS is a cascading language, I think we can leave the `display` / `margin` / `height` stuff off (since that's inherited from the base theme and we don't want to redefine it) and insert only the override we need -- the `width` property.  That should allow us to automagically grow in height (and whatever else) should our theme module ever update.

2023-12-06 20:57 UTC, schaeferka commented on website/assets/scss/_styles_project.scss
> +}
Updated to only add width style for the navbar logo.

2023-12-06 21:09 UTC, btlghrants approved these changes
LGTM!

2023-12-06 21:09 UTC, merged