feat: add resourceVersion tracking for watches & better recovery
defenseunicorns/pepr pull request #453
Opened 2023-12-30 11:33 UTC by jeff-mccoy

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/pepr/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

2023-12-30 15:43 UTC, andrewg-xyz approved these changes, later dismissed

2024-01-01 13:41 UTC, cmwylie19 reviewed
The code lgtm. To be thorough, started a soak test on this at ~8 am that produced an error on the previous versioned due to a timeout.

2024-01-01 15:02 UTC, cmwylie19 approved these changes

2024-01-01 15:25 UTC, cmwylie19 reviewed
I believe I am still hitting the timeout. details to come..

2024-01-01 15:26 UTC, cmwylie19 requested changes
I believe I'm still getting a timeout that only happened after about 2 hours and 7 seconds. I am testing on a k3d cluster using the built manifests:

 [source](https://github.com/cmwylie19/deploy-watcher)
```typescript

const deploymentStrategy: V1DeploymentStrategy = {
  rollingUpdate: {
    maxSurge: "50%",
    maxUnavailable: "50%",
  },
  type: "RollingUpdate",
};

OnSchedule({
  name: "deploy-interrupter",
  every: 1,
  unit: "minutes",
  run: async () => {
    try {
      // Keep changing it to try and capture a watcher silent death
      await K8s(kind.Deployment).Apply(
        {
          metadata: {
            name: "blue",
            namespace: "default",
          },
          spec: {
            replicas: 3,
          },
        },
        {
          force: true,
        },
      );
    } catch (error) {
      Log.error(error, "Failed to change deployment.");
    }
  },
});

When(a.Deployment)
  .IsCreatedOrUpdated()
  .WithName("blue")
  .Watch(async deploy => {
    Log.info(`Deployment ${deploy.metadata?.name} was changed.`);

    // Make it feel like an operator
    if (
      deploy.spec?.replicas !== 2 ||
      deploy.spec?.strategy?.rollingUpdate?.maxSurge !== "50%" ||
      deploy.spec?.strategy?.rollingUpdate?.maxUnavailable !== "50%" ||
      deploy.spec?.strategy?.type !== "RollingUpdate"
    ) {
      try {
        // Reconcile the deployment back to desired state
        await K8s(kind.Deployment).Apply(
          {
            metadata: {
              name: "blue",
              namespace: "default",
            },
            spec: {
              replicas: 2,
              strategy: deploymentStrategy,
            },
          },
          {
            force: true,
          },
        );
      } catch (error) {
        Log.error(error, "Failed to reconcile deployment.");
      }
    }
  });
```

Watcher Logs (Go from Deployment changed to eventually not firing the callback)
```json
{"level":30,"time":1704121201128,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121202687,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":20,"time":1704121202834,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","apiVersion":"pepr.dev/v1","kind":"PeprStore","metadata":{"resourceVersion":"11832"},"msg":"Pepr Store update"}
{"level":30,"time":1704121203104,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121204610,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
{"level":30,"time":1704121204611,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
{"level":20,"time":1704121207836,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Pepr store data received"}
{"level":30,"time":1704121208036,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121208048,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121208054,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121208061,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121208078,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121208078,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":20,"time":1704121212549,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","add:/data/deployment-watcher-deploy-interrupter:{\"lastTimestamp\":\"2024-01-01T15:00:08.019Z\",\"name\":\"deploy-interrupter\"}":{"op":"add","path":"/data/deployment-watcher-deploy-interrupter","value":"{\"lastTimestamp\":\"2024-01-01T15:00:08.019Z\",\"name\":\"deploy-interrupter\"}"},"msg":"Sending updates to Pepr store"}
{"level":30,"time":1704121214608,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
{"level":30,"time":1704121214609,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
{"level":30,"time":1704121216143,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121216163,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121216175,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121216199,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121216201,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121217789,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121218183,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121224603,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
{"level":30,"time":1704121224603,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
{"level":30,"time":1704121231221,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121231232,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121231242,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121231251,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121231262,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121231269,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121232868,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121233251,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121234606,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
{"level":30,"time":1704121234607,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
{"level":30,"time":1704121244605,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
{"level":30,"time":1704121244607,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
{"level":30,"time":1704121246296,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121246313,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121246324,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
{"level":30,"time":1704121246349,"pid":16,"hostname":"pepr-static-test-w [...]

2024-01-01 19:33 UTC, cmwylie19 commented
> I believe I'm still getting a timeout that only happened after about 2 hours and 7 seconds. I am testing on a k3d cluster using the built manifests:
> 
> [source](https://github.com/cmwylie19/deploy-watcher)
> 
> ```ts
> const deploymentStrategy: V1DeploymentStrategy = {
>   rollingUpdate: {
>     maxSurge: "50%",
>     maxUnavailable: "50%",
>   },
>   type: "RollingUpdate",
> };
> 
> OnSchedule({
>   name: "deploy-interrupter",
>   every: 1,
>   unit: "minutes",
>   run: async () => {
>     try {
>       // Keep changing it to try and capture a watcher silent death
>       await K8s(kind.Deployment).Apply(
>         {
>           metadata: {
>             name: "blue",
>             namespace: "default",
>           },
>           spec: {
>             replicas: 3,
>           },
>         },
>         {
>           force: true,
>         },
>       );
>     } catch (error) {
>       Log.error(error, "Failed to change deployment.");
>     }
>   },
> });
> 
> When(a.Deployment)
>   .IsCreatedOrUpdated()
>   .WithName("blue")
>   .Watch(async deploy => {
>     Log.info(`Deployment ${deploy.metadata?.name} was changed.`);
> 
>     // Make it feel like an operator
>     if (
>       deploy.spec?.replicas !== 2 ||
>       deploy.spec?.strategy?.rollingUpdate?.maxSurge !== "50%" ||
>       deploy.spec?.strategy?.rollingUpdate?.maxUnavailable !== "50%" ||
>       deploy.spec?.strategy?.type !== "RollingUpdate"
>     ) {
>       try {
>         // Reconcile the deployment back to desired state
>         await K8s(kind.Deployment).Apply(
>           {
>             metadata: {
>               name: "blue",
>               namespace: "default",
>             },
>             spec: {
>               replicas: 2,
>               strategy: deploymentStrategy,
>             },
>           },
>           {
>             force: true,
>           },
>         );
>       } catch (error) {
>         Log.error(error, "Failed to reconcile deployment.");
>       }
>     }
>   });
> ```
> 
> Watcher Logs (Go from Deployment changed to eventually not firing the callback)
> 
> ```json
> {"level":30,"time":1704121201128,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121202687,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":20,"time":1704121202834,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","apiVersion":"pepr.dev/v1","kind":"PeprStore","metadata":{"resourceVersion":"11832"},"msg":"Pepr Store update"}
> {"level":30,"time":1704121203104,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121204610,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
> {"level":30,"time":1704121204611,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
> {"level":20,"time":1704121207836,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Pepr store data received"}
> {"level":30,"time":1704121208036,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121208048,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121208054,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121208061,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121208078,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121208078,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":20,"time":1704121212549,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","add:/data/deployment-watcher-deploy-interrupter:{\"lastTimestamp\":\"2024-01-01T15:00:08.019Z\",\"name\":\"deploy-interrupter\"}":{"op":"add","path":"/data/deployment-watcher-deploy-interrupter","value":"{\"lastTimestamp\":\"2024-01-01T15:00:08.019Z\",\"name\":\"deploy-interrupter\"}"},"msg":"Sending updates to Pepr store"}
> {"level":30,"time":1704121214608,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
> {"level":30,"time":1704121214609,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
> {"level":30,"time":1704121216143,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121216163,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121216175,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121216199,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121216201,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121217789,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121218183,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121224603,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
> {"level":30,"time":1704121224603,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
> {"level":30,"time":1704121231221,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121231232,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121231242,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121231251,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121231262,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121231269,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121232868,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121233251,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121234606,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
> {"level":30,"time":1704121234607,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
> {"level":30,"time":1704121244605,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"1 ms"}
> {"level":30,"time":1704121244607,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","method":"GET","url":"/healthz","status":200,"duration":"0 ms"}
> {"level":30,"time":1704121246296,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deployment blue was changed."}
> {"level":30,"time":1704121246313,"pid":16,"hostname":"pepr-static-test-watcher-6cd957b5b-h765s","msg":"Deploym [...]

2024-01-01 19:34 UTC, cmwylie19 approved these changes
lgtm

2024-01-01 21:22 UTC, merged